name: CI (Windows)

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build & Test on Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          goos: windows
          goarch: amd64
          binary_name: "synclink"
          sha256sum: true
          
