name: CI (Windows)

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build & Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'       # 或者你项目使用的 Go 版本
          check-latest: true

      - name: Build Windows binary
        run: |
          # 设置环境变量，交叉编译目标为 Windows AMD64
          set GOOS=windows
          set GOARCH=amd64
          # 构建
          go build -o build/synclink.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: synclink-windows-amd64
          path: build/synclink.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          draft: true
          token: ${{ secrets.ACCESS_TOKEN }}
