# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-windows-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        goos: windows
        binary_name: "synclink"
        sha256sum: true
        goarch: amd64
