name: CI

on:
  release:
    types:
      - created

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          binary_name: "synclink"
          sha256sum: true
          extra_files: LICENSE README.md config.json
          
